[package]
name = "hello_rust"
version = "0.1.0"
authors = ["basalt79"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riker = "0.4.1"